version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - ../storage:/web_application/storage

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
